#!/usr/bin/env python3
"""
Antigravity Subagent Transcript Log Token Harvester

Parses the empirical JSONL transcript files generated by Antigravity subagent sessions,
extracting exact byte counts, character lengths, tool ingestion payloads, and estimated
tokens (both per-turn context accumulation and aggregate LLM roundtrips).
"""

import json
import os
import sys
from typing import Dict, Any, List

def parse_transcript(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        lines = [line.strip() for line in f if line.strip()]

    steps = [json.loads(line) for line in lines]
    
    # Track turns
    # In Antigravity multi-turn agent conversations:
    # On each turn where type == "PLANNER_RESPONSE", the LLM is invoked.
    # The prompt sent to the LLM is the concatenation of all prior messages up to that step.
    
    llm_calls = 0
    cumulative_prompt_chars = 0
    cumulative_gen_chars = 0
    cumulative_thinking_chars = 0
    tool_input_chars = 0
    tool_output_chars = 0
    
    tool_breakdown = {}
    history_chars = 0
    turn_details = []

    for i, step in enumerate(steps):
        s_type = step.get("type", "")
        source = step.get("source", "")
        content = step.get("content", "") or ""
        thinking = step.get("thinking", "") or ""
        tool_calls = step.get("tool_calls", []) or []

        step_chars = len(content)

        if s_type == "USER_INPUT":
            history_chars += step_chars
        elif s_type == "GENERIC":  # Tool execution output returned to model
            history_chars += step_chars
            tool_output_chars += step_chars
        elif s_type == "PLANNER_RESPONSE":
            llm_calls += 1
            # The prompt for this call is current history_chars
            prompt_for_call = history_chars
            cumulative_prompt_chars += prompt_for_call
            
            # The generation for this call is thinking + tool_calls JSON + content
            tool_args_str = "".join(json.dumps(tc.get("args", {})) for tc in tool_calls)
            gen_chars_this_turn = len(thinking) + len(tool_args_str) + len(content)
            
            cumulative_gen_chars += gen_chars_this_turn
            cumulative_thinking_chars += len(thinking)
            tool_input_chars += len(tool_args_str)
            
            # Record tool call types
            for tc in tool_calls:
                tname = tc.get("name", "unknown")
                args = tc.get("args", {})
                arg_bytes = len(json.dumps(args))
                if tname not in tool_breakdown:
                    tool_breakdown[tname] = {"count": 0, "args_bytes": 0, "output_bytes": 0}
                tool_breakdown[tname]["count"] += 1
                tool_breakdown[tname]["args_bytes"] += arg_bytes

            turn_details.append({
                "turn": llm_calls,
                "step_index": step.get("step_index", i),
                "prompt_chars": prompt_for_call,
                "generation_chars": gen_chars_this_turn,
                "thinking_chars": len(thinking),
                "tools_called": [tc.get("name", "") for tc in tool_calls]
            })

            # Assistant response is added to history for subsequent turns
            history_chars += len(content) + len(tool_args_str)

    # Calculate token estimates
    # Standard code/JSON ratio in Gemini/OpenAI subword tokenizers is approx 3.6 chars/token
    prompt_tokens_est = int(round(cumulative_prompt_chars / 3.6))
    gen_tokens_est = int(round(cumulative_gen_chars / 3.6))
    total_tokens_est = prompt_tokens_est + gen_tokens_est
    final_context_tokens_est = int(round(history_chars / 3.6))

    return {
        "path": path,
        "total_steps": len(steps),
        "llm_calls": llm_calls,
        "cumulative_prompt_chars": cumulative_prompt_chars,
        "cumulative_gen_chars": cumulative_gen_chars,
        "cumulative_thinking_chars": cumulative_thinking_chars,
        "final_context_chars": history_chars,
        "tool_output_chars": tool_output_chars,
        "tool_input_chars": tool_input_chars,
        "prompt_tokens_est": prompt_tokens_est,
        "gen_tokens_est": gen_tokens_est,
        "total_tokens_est": total_tokens_est,
        "final_context_tokens_est": final_context_tokens_est,
        "tool_breakdown": tool_breakdown,
        "turn_details": turn_details
    }

def print_comparison(file_res: Dict[str, Any], ast_res: Dict[str, Any]):
    print("=" * 80)
    print("EMPIRICAL SUBAGENT LOG TOKEN HARVESTER: FILE-BASED VS. COSM AST SURGERY")
    print("=" * 80)
    print()
    print(f"{'Metric':<38} | {'File-Based Agent':<18} | {'Cosm AST Surgeon':<18} | {'Delta / Reduction':<16}")
    print("-" * 80)

    # Normalized per-turn metrics
    f_avg_prompt_chars = file_res["cumulative_prompt_chars"] / max(file_res["llm_calls"], 1)
    a_avg_prompt_chars = ast_res["cumulative_prompt_chars"] / max(ast_res["llm_calls"], 1)
    f_avg_prompt_tokens = file_res["prompt_tokens_est"] / max(file_res["llm_calls"], 1)
    a_avg_prompt_tokens = ast_res["prompt_tokens_est"] / max(ast_res["llm_calls"], 1)

    metrics = [
        ("Total Subagent Steps", file_res["total_steps"], ast_res["total_steps"], False),
        ("LLM Invocations (Turns)", file_res["llm_calls"], ast_res["llm_calls"], False),
        ("Final Context Window (Chars)", file_res["final_context_chars"], ast_res["final_context_chars"], True),
        ("Final Context Window (Tokens est.)", file_res["final_context_tokens_est"], ast_res["final_context_tokens_est"], True),
        ("Average Context per Turn (Chars)", int(f_avg_prompt_chars), int(a_avg_prompt_chars), True),
        ("Average Context per Turn (Tokens est.)", int(f_avg_prompt_tokens), int(a_avg_prompt_tokens), True),
        ("Cumulative Prompt Ingested (Chars)", file_res["cumulative_prompt_chars"], ast_res["cumulative_prompt_chars"], True),
        ("Cumulative Prompt Tokens (est.)", file_res["prompt_tokens_est"], ast_res["prompt_tokens_est"], True),
        ("Tool Output Payload Ingested (Chars)", file_res["tool_output_chars"], ast_res["tool_output_chars"], True),
        ("Cumulative Generation Chars", file_res["cumulative_gen_chars"], ast_res["cumulative_gen_chars"], True),
        ("Cumulative Generation Tokens (est.)", file_res["gen_tokens_est"], ast_res["gen_tokens_est"], True),
        ("Total Billed Tokens Consumed (est.)", file_res["total_tokens_est"], ast_res["total_tokens_est"], True),
    ]

    for label, f_val, a_val, is_reduction in metrics:
        if is_reduction:
            if f_val > 0:
                pct = ((f_val - a_val) / f_val) * 100.0
                sign = "-" if pct > 0 else "+"
                delta_str = f"{sign}{abs(pct):.1f}%"
            else:
                delta_str = "N/A"
        else:
            diff = a_val - f_val
            sign = "+" if diff > 0 else ""
            delta_str = f"{sign}{diff}"
        
        print(f"{label:<38} | {f_val:<18,d} | {a_val:<18,d} | {delta_str:<16}")

    print("-" * 80)
    print()
    print("TURN-BY-TURN PROMPT ACCUMULATION (CHARS):")
    max_turns = max(len(file_res["turn_details"]), len(ast_res["turn_details"]))
    print(f"{'Turn':<6} | {'File-Based Prompt Chars':<25} | {'Cosm AST Prompt Chars':<25} | {'Instant Reduction':<18}")
    print("-" * 80)
    for t in range(max_turns):
        f_turn = file_res["turn_details"][t] if t < len(file_res["turn_details"]) else None
        a_turn = ast_res["turn_details"][t] if t < len(ast_res["turn_details"]) else None

        f_p = f"{f_turn['prompt_chars']:,}" if f_turn else "—"
        a_p = f"{a_turn['prompt_chars']:,}" if a_turn else "—"
        
        if f_turn and a_turn and f_turn['prompt_chars'] > 0:
            diff_pct = ((f_turn['prompt_chars'] - a_turn['prompt_chars']) / f_turn['prompt_chars']) * 100.0
            diff_str = f"-{diff_pct:.1f}%" if diff_pct > 0 else f"+{abs(diff_pct):.1f}%"
        else:
            diff_str = "—"
            
        print(f"{t+1:<6} | {f_p:<25} | {a_p:<25} | {diff_str:<18}")

    print("-" * 80)
    print()
    print("TOOL BREAKDOWN:")
    print("  File-Based Agent Tools:")
    for tname, stats in file_res["tool_breakdown"].items():
        print(f"    • {tname:<22}: {stats['count']} calls, {stats['args_bytes']:,} args chars")
    print("  Cosm AST Agent Tools:")
    for tname, stats in ast_res["tool_breakdown"].items():
        print(f"    • {tname:<22}: {stats['count']} calls, {stats['args_bytes']:,} args chars")

if __name__ == "__main__":
    file_log = sys.argv[1] if len(sys.argv) > 1 else "test/agents/transcripts/subagent_a_file_full.jsonl"
    ast_log = sys.argv[2] if len(sys.argv) > 2 else "test/agents/transcripts/subagent_b_ast_full.jsonl"

    if not os.path.exists(file_log) or not os.path.exists(ast_log):
        print(f"Error: Log files not found: {file_log}, {ast_log}")
        sys.exit(1)

    f_res = parse_transcript(file_log)
    a_res = parse_transcript(ast_log)
    print_comparison(f_res, a_res)
