package llm

import (
	"context"
	"encoding/json"
	"time"
)

// Role defines the participant role in a conversation.
type Role string

const (
	RoleSystem    Role = "system"
	RoleUser      Role = "user"
	RoleAssistant Role = "assistant"
	RoleTool      Role = "tool"
)

// Message represents a single message in an LLM conversation history.
type Message struct {
	Role         Role        `json:"role"`
	Content      string      `json:"content"`
	ToolCalls    []ToolCall  `json:"tool_calls,omitempty"`
	ToolCallID   string      `json:"tool_call_id,omitempty"`
	Name         string      `json:"name,omitempty"`
	Timestamp    time.Time   `json:"timestamp,omitempty"`
}

// ToolDefinition defines a callable function/tool provided to the LLM.
type ToolDefinition struct {
	Name        string                 `json:"name"`
	Description string                 `json:"description"`
	Parameters  map[string]interface{} `json:"parameters"` // JSON Schema representation
}

// ToolCall represents a tool execution invocation emitted by the LLM.
type ToolCall struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Arguments string `json:"arguments"` // JSON-encoded arguments string
}

// ParseArguments parses the JSON-encoded arguments into a map or target struct.
func (tc *ToolCall) ParseArguments(target interface{}) error {
	if tc.Arguments == "" {
		return nil
	}
	return json.Unmarshal([]byte(tc.Arguments), target)
}

// ToolResult encapsulates the outcome of executing a ToolCall.
type ToolResult struct {
	ToolCallID string        `json:"tool_call_id"`
	Name       string        `json:"name"`
	Output     string        `json:"output"`
	Error      string        `json:"error,omitempty"`
	Success    bool          `json:"success"`
	Duration   time.Duration `json:"duration"`
}

// TokenUsage records the token consumption metrics for an LLM call.
type TokenUsage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

// Response represents the output generated by an LLM provider.
type Response struct {
	Content      string      `json:"content"`
	ToolCalls    []ToolCall  `json:"tool_calls,omitempty"`
	FinishReason string      `json:"finish_reason,omitempty"`
	Usage        TokenUsage  `json:"usage"`
	Model        string      `json:"model"`
	RawPayload   string      `json:"raw_payload,omitempty"`
}

// HasToolCalls returns true if the LLM response requested one or more tool executions.
func (r *Response) HasToolCalls() bool {
	return len(r.ToolCalls) > 0
}

// GenerateOptions contains runtime configuration options for the LLM request.
type GenerateOptions struct {
	Model             string   `json:"model,omitempty"`
	Temperature       *float64 `json:"temperature,omitempty"`
	TopP              *float64 `json:"top_p,omitempty"`
	MaxTokens         *int     `json:"max_tokens,omitempty"`
	StopSequences     []string `json:"stop_sequences,omitempty"`
	SystemInstruction string   `json:"system_instruction,omitempty"`
}

// LLMProvider is the universal interface for language model backends.
type LLMProvider interface {
	// Generate produces a model response given message history and available tools.
	Generate(ctx context.Context, messages []Message, tools []ToolDefinition, opts GenerateOptions) (*Response, error)
	// ModelName returns the identifier of the primary model configured.
	ModelName() string
}
